# Generated by Django 4.1.1 on 2022-10-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_about_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='achievements',
        ),
        migrations.AddField(
            model_name='achievements',
            name='achievement_description',
            field=models.TextField(default='h', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievements',
            name='title',
            field=models.TextField(default='heelo', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievements',
            name='university',
            field=models.TextField(default='bishop', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievements',
            name='year',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
