# Generated by Django 4.1.1 on 2022-10-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_achievements_achievement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasicdetails',
            name='profile_image',
            field=models.ImageField(default='g', upload_to='profile/'),
            preserve_default=False,
        ),
    ]
