# Generated by Django 4.1.2 on 2023-01-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_userbasicdetails_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsBrideProgramm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('university', models.TextField(blank=True, default=None, max_length=100, null=True)),
                ('courseInfo', models.TextField(blank=True, default=None, max_length=10000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='aboutImg',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='bg_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ProjectImg/'),
        ),
        migrations.AddField(
            model_name='workexperiences',
            name='exp_bg_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ExpBackground/'),
        ),
        migrations.AddField(
            model_name='workexperiences',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ExpImg/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(blank=True, default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=5001),
        ),
    ]
